version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # There is no support for recursing alternate folders or wildcards in dependabot, see:
  # https://github.com/dependabot/dependabot-core/issues/5137
  # https://github.com/dependabot/dependabot-core/issues/5047
  - package-ecosystem: "github-actions"
    directory: ".github/actions/goodbye"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: ".github/actions/hello"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: ".github/actions/nested_printer"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: ".github/actions/printer"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: ".github/actions/update_me"
    schedule:
      interval: "daily"
