version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/actions/goodbye"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/actions/hello"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/actions/nested_printer"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/actions/printer"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/actions/update_me"
    schedule:
      interval: "daily"
