name: update-me
description: "Outdated checkout to test dependabot."
author: 'Fabian Kammel'
runs:
  using: 'composite'
  steps:
    - name: Check out repository
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
