name: update-me
description: "Outdated checkout to test dependabot."
author: 'Fabian Kammel'
runs:
  using: 'composite'
  steps:
    - name: Check out repository
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
