name: update-me
description: "Outdated checkout to test dependabot."
author: 'Fabian Kammel'
runs:
  using: 'composite'
  steps:
    - name: Check out repository
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
