name: hello
description: "Hello & generate number, I'm totally well designed."
author: 'Fabian Kammel'
branding:
  color: purple
  icon: airplay
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: 'composite'
  steps:
  - name: Greeter
    run: echo Hello ${{ inputs.who-to-greet }}.
    shell: bash
  - name: Random number generator
    id: random-number-generator
    run: echo "::set-output name=random-id::$(echo $RANDOM)"
    shell: bash
  - name: Error producer
    run: exit 42
    shell: bash
  - name: Error handler
    if: ${{ failure() }}
    uses: ./.github/actions/goodbye
