name: hello
description: "Greet with custom greeting."
author: 'Fabian Kammel'
inputs:
  how-to-greet:
    description: 'Greeting word or phrase'
    required: true
    default: 'Hello'
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: 'composite'
  steps:
  - name: Greeter
    run: echo ${{ inputs.how-to-greet }} ${{ inputs.who-to-greet }}.
    shell: bash
