# name: calculator

# on:
#   push:

# permissions: {}

# env:
#   GO_VERSION: "1.19.2"
#   SYFT_VERSION: "0.58.0"
#   GRYPE_VERSION: "0.50.2"
#   IMAGE_REF: "ghcr.io/${{ github.repository }}/calculator"

# jobs:
#   unit-tests:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       checks: write
#     steps:
#       - name: Check out repository
#         uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
#       - name: Setup Go
#         uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # tag=v3.3.0
#         with:
#           go-version: ${{ env.GO_VERSION }}
#       - name: Install go-junit-report
#         run: go install github.com/jstemmer/go-junit-report/v2@v2.0.0
#       - name: Run Unit Tests
#         run: go test -v 2>&1 ./... | go-junit-report -set-exit-code > report.xml
#       - name: Test Report
#         uses: dorny/test-reporter@c9b3d0e2bd2a4e96aaf424dbaa31c46b42318226 # tag=v1.6.0
#         if: always()
#         with:
#           name: calculator tests
#           path: report.xml
#           reporter: java-junit

#   build-calculator:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out repository
#         uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
#       - name: Setup Go
#         uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # tag=v3.3.0
#         with:
#           go-version: ${{ env.GO_VERSION }}
#       - name: Build Calculator
#         run: |
#           CGO_ENABLED=0 go build \
#             -o calculator \
#             -trimpath -buildvcs=false -ldflags "-s -w -buildid=''" \
#             ./cmd/calculator
#       - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3.1.0
#         with:
#           name: calculator
#           path: calculator
#       - name: Compute calculator hash
#         id: calculator-hash
#         run: |
#           CALCULATOR_HASH=$(sha256sum calculator | base64 -w0)
#           echo CALCULATOR_HASH=${CALCULATOR_HASH} >> $GITHUB_OUTPUT
#           cat $GITHUB_OUTPUT

#   sign-calculator:
#     runs-on: ubuntu-latest
#     needs:
#       - build-calculator
#     steps:
#       - name: Check out repository
#         uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
#       - name: Install Cosign & Rekor CLI
#         uses: sigstore/sigstore-installer@initial
#         with:
#           cosign-version: "v1.12.1"
#           rekor-cli-version: "v0.12.2"
#       - name: Download calculator binary
#         uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3.0.0
#         with:
#           name: calculator
#       - name: Sign calculator
#         run: |
#           set -ex
#           set -o pipefail
#           cosign sign-blob --key env://COSIGN_PRIVATE_KEY calculator > calculator.sig
#           # Verify - As documentation & check
#           # Local Signature (input: artifact, key, signature)
#           cosign verify-blob --key env://COSIGN_PUBLIC_KEY --signature calculator.sig calculator
#           # Transparency Log Signature (input: artifact, key)
#           uuid=$(rekor-cli search --artifact calculator | tail -n 1)
#           sig=$(rekor-cli get --uuid=$uuid --format=json | jq -r .Body.HashedRekordObj.signature.content)
#           cosign verify-blob --key env://COSIGN_PUBLIC_KEY --signature <(echo $sig) calculator
#         shell: bash
#         env:
#           COSIGN_EXPERIMENTAL: 1
#           COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
#           COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
#           COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
#       - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3.1.0
#         with:
#           name: calculator.sig
#           path: calculator.sig

#   build-calculator-image:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write
#     needs:
#       - build-calculator
#     steps:
#       - name: Check out repository
#         uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
#       - name: Docker metadata
#         id: meta
#         uses: docker/metadata-action@12cce9efe0d49980455aaaca9b071c0befcdd702 # tag=v4.1.0
#         with:
#           images: |
#             ${{ env.IMAGE_REF }}
#           tags: |
#             type=raw,value=latest,enable={{is_default_branch}}
#             type=sha,prefix=
#             type=sha,format=long,prefix=
#             type=semver,pattern={{version}}
#             type=ref,event=branch
#       - name: Log in to ghcr.io
#         id: docker-login
#         uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2.1.0
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#       - name: Download calculator binary
#         uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3.0.0
#         with:
#           name: calculator
#       - name: look around
#         run: |
#           ls -la
#           tree . || true
#       - name: Build and push container image
#         id: build-container-image
#         uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5 # tag=v3.2.0
#         with:
#           context: .
#           file: cmd/calculator/Dockerfile
#           push: true
#           tags: ${{ steps.meta.outputs.tags }}

#   sbom-image:
#     runs-on: ubuntu-latest
#     needs:
#       - build-calculator-image
#     permissions: write-all
#     steps:
#       - name: Log in to ghcr.io
#         id: docker-login
#         uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2.1.0
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#       - name: Install Cosign CLI
#         uses: sigstore/cosign-installer@7cc35d7fdbe70d4278a0c96779081e6fac665f88 # tag=v2.8.0
#       # Currently not supported in action: https://github.com/anchore/sbom-action/issues/153
#       # Need to download syft and run commands directly
#       - name: Download syft & grype
#         run: |
#           curl -LO https://github.com/anchore/syft/releases/download/v${SYFT_VERSION}/syft_${SYFT_VERSION}_linux_amd64.tar.gz
#           tar -xzf syft_${SYFT_VERSION}_linux_amd64.tar.gz
#           ./syft version
#           curl -LO https://github.com/anchore/grype/releases/download/v${GRYPE_VERSION}/grype_${GRYPE_VERSION}_linux_amd64.tar.gz
#           tar -xzf grype_${GRYPE_VERSION}_linux_amd64.tar.gz
#           ./grype version
#           echo $(pwd) >> $GITHUB_PATH
#       - name: Generate SBOM
#         run: |
#           set -ex
#           echo "$COSIGN_PRIVATE_KEY" > cosign.key
#           syft attest --key cosign.key ${{ env.IMAGE_REF }}:${{ github.sha }} -o cyclonedx-json > calculator.att.json
#           cat calculator.att.json
#           echo "${{ env.IMAGE_REF }}:${{ github.sha }}"
#           cosign attach attestation ${{ env.IMAGE_REF }}:${{ github.sha }} --attestation calculator.att.json
#           # TODO: Enable verification of attestation
#           # https://sigstore.slack.com/archives/C01PZKDL4DP/p1665761799380409
#           # cosign verify-attestation ${{ env.IMAGE_REF }}:${{ github.sha }} --type cyclonedx --key env://COSIGN_PUBLIC_KEY
#           grype ${{ env.IMAGE_REF }}:${{ github.sha }} --fail-on critical --only-fixed
#         shell: bash
#         env:
#           COSIGN_EXPERIMENTAL: 1
#           COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
#           COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
#           COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

#   # TODO: Generate provenance
#   # TODO: Sign provenance
#   # TODO: Add signed provenance to container registry

#   sign-calculator-image:
#     runs-on: ubuntu-latest
#     needs:
#       - build-calculator-image
#     permissions:
#       contents: read
#       packages: write
#     steps:
#       - name: Check out repository
#         uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
#       - name: Install Cosign CLI
#         uses: sigstore/cosign-installer@7cc35d7fdbe70d4278a0c96779081e6fac665f88 # tag=v2.8.0
#       - name: Log in to ghcr.io
#         id: docker-login
#         uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2.1.0
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#       - name: Sign calculator-image
#         run: |
#           cosign sign \
#             --key env://COSIGN_PRIVATE_KEY \
#             ${{ env.IMAGE_REF }}
#           cosign verify \
#             --key env://COSIGN_PUBLIC_KEY \
#             ${{ env.IMAGE_REF }}
#         shell: bash
#         env:
#           COSIGN_EXPERIMENTAL: 1
#           COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
#           COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
#           COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

#   provenance:
#     permissions:
#       actions: read
#       contents: write
#       id-token: write
#     needs:
#       - build-calculator
#     uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@dc705baf82c5178c9d1555594b0652f569e22779 # tag=v1.2.1
#     with:
#       base64-subjects: "${{ needs.build-calculator.outputs.CALCULATOR_HASH }}"
#       # compile-generator: true

#   show-provenance:
#     runs-on: ubuntu-latest
#     needs:
#       - provenance
#     steps:
#       - name: Download provenance
#         uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3.0.0
#         with:
#           name: ${{ needs.provenance.outputs.provenance-name }}
#       - name: Show provenance
#         run: |
#           ls -la
#           ls -R
#           tree .

#   release:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#     needs:
#       - build-calculator
#       - sign-calculator
#       - unit-tests
#     if: startsWith(github.ref, 'refs/tags/v')
#     steps:
#       - name: Download calculator binary
#         uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3.0.0
#         with:
#           name: calculator
#       - name: Download calculator signature
#         uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3.0.0
#         with:
#           name: calculator.sig
#       - name: Write public key
#         run: |
#           echo "$COSIGN_PUBLIC_KEY" > cosign.pub
#         env:
#           COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
#       - name: Release
#         uses: ncipollo/release-action@4c75f0f2e4ae5f3c807cf0904605408e319dcaac # tag=v1.11.1
#         with:
#           draft: true
#           artifacts: "calculator,calculator.sig,cosign.pub"
