name: commit-and-trigger

on:
  workflow_dispatch:

permissions: {}

env:
  GO_VERSION: "1.19.2"
  SYFT_VERSION: "0.58.0"
  GRYPE_VERSION: "0.50.2"
  IMAGE_REF: "ghcr.io/${{ github.repository }}/calculator"

jobs:
  commit-and-trigger:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          token: ${{ secrets.COMMIT_AND_TRIGGER_PAT }}
          ref: ${{ github.head_ref }}
      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: go mod tidy
        run: |
          go mod tidy
      - name: Commit changes
        id: commit
        uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b # tag=v9.1.1
      - name: Summary
        run: |
          echo Did commit? ${{ steps.commit.outputs.committed }}
          echo Commit SHA: ${{ steps.commit.outputs.commit_sha }}
          echo Did push? ${{ steps.commit.outputs.pushed }}
