name: detect-dbg

on:
  workflow_dispatch:

permissions: {}

jobs:
  detect-dbg:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Dump contexts
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          ENV_CONTEXT: ${{ toJSON(env) }}
          JOB_CONTEXT: ${{ toJSON(job) }}
          STEPS_CONTEXT: ${{ toJSON(steps) }}
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: |
          echo ${{ runner.debug }}
          echo GITHUB_CONTEXT:
          echo "$GITHUB_CONTEXT"
          echo ENV_CONTEXT:
          echo "$ENV_CONTEXT"
          echo JOB_CONTEXT:
          echo "$JOB_CONTEXT"
          echo STEPS_CONTEXT:
          echo "$STEPS_CONTEXT"
          echo RUNNER_CONTEXT:
          echo "$RUNNER_CONTEXT"
          echo ENV:
          env
