name: detect-dbg

on:
  push:

permissions: {}

jobs:
  detect-dbg:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - name: Is debug?
        run: |
          echo ACTIONS_RUNNER_DEBUG: $ACTIONS_RUNNER_DEBUG
          echo ACTIONS_STEP_DEBUG: $ACTIONS_STEP_DEBUG
