name: dump-info

on:
  push:

jobs:
  dump-info:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: break it
        run: exit 42
        shell: bash
      - name: Notify channel
        if: failure()
        run: |
          ls -la
          echo path: ${{ github.action_path }}
          cd ${{ github.action_path }}
          ls -la
          curl                                          \
            -H "Content-Type: application/json"         \
            -d @teams-payload.json                      \
            "${{ secrets.MS_TEAMS_WEBHOOK_URI }}"
        shell: bash
