name: dump-info

on:
  push:

jobs:
  dump-info:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: break it
        run: exit 42
        shell: bash
      - name: Notify channel
        run: |
          curl                                          \
            -H "Content-Type: application/json"         \
            -d "{\"text\": \"pipeline broke"}"          \
            "${{ secrets.MS_TEAMS_WEBHOOK_URI }}"
        shell: bash
