name: dump-info

on:
  push:

jobs:
  dump-info:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: break it
        run: exit 42
        shell: bash
      - name: Notify channel
        if: failure()
        run: |
          export TEAMS_JOB_NAME=${{ github.job }}
          export TEAMS_RUN_ID=${{ github.run_id }}
          envsubst < teams-payload.json > to-be-send.json
          curl                                          \
            -H "Content-Type: application/json"         \
            -d @to-be-send.json                      \
            "${{ secrets.MS_TEAMS_WEBHOOK_URI }}"
        shell: bash
        working-directory: .github/workflows
