name: dump-info

on:
  push:

jobs:
  dump-info:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Context info dump
        run: |
          echo github.action: ${{ github.action }}
          echo github.job: ${{ github.job }}
          echo github.run_id: ${{ github.run_id }}
        shell: bash
