name: manual-greet

on:
  workflow_dispatch:
    inputs:
      how-to-greet:
        description: 'Greeting word or phrase'
        required: true
        default: 'Hello'
      who-to-greet:
        description: 'Who to greet'
        required: true
        default: 'World'

jobs:
  manual-greet:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - id: greeter
        name: Use my local greeter
        uses: ./.github/actions/hello
        with:
          who-to-greet: ${{ github.event.inputs.how-to-greet }}
          how-to-greet: ${{ github.event.inputs.who-to-greet }}
      - id: printer
        name: Print with printer
        uses: ./.github/actions/printer
        env:
          TO_PRINT: "normal printer call"
      - id: nested_printer
        name: Print with nested_printer
        uses: ./.github/actions/nested_printer
        env:
          TO_PRINT: "nested printer call"
      - name: Always goodbye
        if: ${{ always() && !env.ACT }}
        uses: ./.github/actions/goodbye
