name: pass-outputs

on:
  workflow_dispatch:

permissions: {}

jobs:
  generate-output:
    runs-on: ubuntu-22.04
    outputs:
      calculator-hash: ${{ steps.calculator-hash.outputs.calculator-hash }}
    steps:
      - name: Compute calculator hash
        id: calculator-hash
        run: |
          echo "foobar" > calculator
          CALCULATOR_HASH=$(sha256sum calculator | base64 -w0)
          echo calculator-hash=${CALCULATOR_HASH} >> $GITHUB_OUTPUT

  read-output:
    runs-on: ubuntu-22.04
    needs:
      - generate-output
    steps:
      - name: Read hash
        run: |
          echo ${{ needs.generate-output.outputs.calculator-hash }}
