name: learn-github-actions

on: [push]

jobs:
  some-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use my local greeter
        uses: ./.github/actions/hello
        with:
          who-to-greet: Fabian
