name: pass-outputs

on:
  push:

permissions: {}

jobs:
  generate-output:
    runs-on: ubuntu-latest
    outputs:
      calculator-hash: ${{ steps.calculator-hash.outputs.calculator-hash }}
    steps:
      - name: Compute calculator hash
        id: calculator-hash
        run: |
          echo "foobar" > calculator
          calculator-hash=$(sha256sum calculator | base64 -w0)
          echo calculator-hash=${calculator-hash} >> $GITHUB_OUTPUT

  read-output:
    runs-on: ubuntu-latest
    needs:
      - generate-output
    steps:
      - name: Read hash
        run: |
          echo ${{ needs.generate-output.outputs.calculator-hash }}
