name: pass-outputs

on:
  push:

permissions: {}

jobs:
  generate-output:
    runs-on: ubuntu-latest
    steps:
      - name: Compute calculator hash
        id: calculator-hash
        run: |
          echo "foobar" > calculator
          CALCULATOR_HASH=$(sha256sum calculator | base64 -w0)
          echo CALCULATOR_HASH=${CALCULATOR_HASH} >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

  read-output:
    runs-on: ubuntu-latest
    needs:
      - generate-output
    steps:
      - name: Read hash
        run: |
          echo ${{ needs.generate-output.outputs.CALCULATOR_HASH }}
