name: ternary

on:
  workflow_dispatch:

permissions: {}

jobs:
  ternary:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - name: Decide
        run: |
          echo ${MSG}
        env:
          MSG: ${{ github.ref_protected && 'PROD STRING' || 'DEV STRING' }}
