name: ternary

on:
  workflow_dispatch:

permissions: {}

jobs:
  ternary:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Decide
        run: |
          echo ${MSG}
        env:
          MSG: ${{ github.ref_protected && 'PROD STRING' || 'DEV STRING' }}
