name: calculator

on:
  push:
  # workflow_dispatch:

permissions: {}

jobs:
  ternary:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - name: Decide
        run: |
          echo ${{ github }}
          echo ${{ github.ref }}
          echo hello
        env:
          MSG: ${{ startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'release/v') && secrets.COSIGN_PUBLIC_KEY || secrets.DEV_COSIGN_PUBLIC_KEY }}
